---
- hosts: wordpress
  become: true
  become_method: sudo

  vars:
    wp_db_name: wordpress
    wp_db_user: wordpress
    wp_db_pass: wordpress
    mysql_root_password : root
  roles:
    - apache2
    - mysql
    - php
    - wordpress