---
- name: Install mysql server
  apt:
    name: mysql-server
    state: present
    force: yes
    update_cache: yes

- name: Install python mysql dependencies
  apt:
    name: python3-pymysql
    state: present

- name: Set mySQL root password
  command: mysql -u root -e 'ALTER USER "root"@"localhost" IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";'
  when: mysql_root_password is defined
  ignore_errors: true

- name: Create wordpress database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create mysql wordpress user
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_pass }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: localhost
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"