---
- name: Install php8.3
  apt:
    name:
      - "php8.3"
      - "php8.3-fpm"
      - "php8.3-mbstring"
      - "php-pear"
      - "php8.3-fpm"
      - "php-common"
      - "php-gd"
      - "php-mysql"
      - "php-enchant"
      - "hunspell"

    state: present
    force: yes
    update_cache: yes

- name: set php-fpm
  command: "a2enmod proxy_fcgi setenvif && a2enconf php8.3-fpm"
  notify: 
    - restart apache2
    - restart php-fpm
  ignore_errors: yes